version: "3.1"
services:
  app:
    build: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db_data:
